provider = "keycloak"
http_address = "0.0.0.0:4180"

client_id = "geostrat-client"
client_secret = "9SOuKBohMpi7QuksYZfv5o6mp3hYmu70"
redirect_url = "http://localhost:4180/oauth2/callback"
oidc_issuer_url = "http://localhost:8081/realms/geostrat"

skip_oidc_discovery = false

scope = "openid profile email"
email_domains = ["*"]
skip_provider_button = false

upstreams = [
    "http://geostrat-app:8080"
]

api_routes = [
    "^/api/"
]

skip_auth_routes = [
    "GET=^/$",
    "GET=^/index\\.html$",
    "GET=^/login$",
    "GET=^/login\\.html$",
    "GET=^/css/.*$",
    "GET=^/js/.*$",
    "GET=^/api/auth/me$",
    "GET=^/api/players$",
    "GET=^/api/map$",
    "GET=^/api/game-state$",
    "GET=^/api/user/leaderboard$"
]

 session_store_type = "redis"
 redis_connection_url = "redis://:redis123@redis:6379"

pass_user_headers = true
pass_basic_auth = false
pass_access_token = true
pass_authorization_header = true
set_authorization_header = true
set_xauthrequest = true

cookie_name = "_oauth2_proxy_geostrat"
cookie_secret = "zrbbihrkgmheprnxrmexorfygxvadiut"
cookie_secure = false
cookie_httponly = true
cookie_samesite = "lax"
cookie_csrf_expire = "15m"
cookie_csrf_per_request = true
cookie_csrf_samesite = "lax"

whitelist_domains = [
    "localhost"
]