provider = "oidc"
http_address = "0.0.0.0:4180"

client_id = "oauth2-proxy"
client_secret = "8UQK6oF3SkdGs7TnWTQOKiXeS165O0Ln"
redirect_url = "http://localhost:4180/oauth2/callback"
oidc_issuer_url = "http://localhost:8082/realms/geostrat"

skip_oidc_discovery = true
insecure_oidc_allow_unverified_email = true
insecure_oidc_skip_issuer_verification = true
login_url = "http://localhost:8082/realms/geostrat/protocol/openid-connect/auth"

redeem_url = "http://host.docker.internal:8082/realms/geostrat/protocol/openid-connect/token"
oidc_jwks_url = "http://host.docker.internal:8082/realms/geostrat/protocol/openid-connect/certs"
profile_url = "http://host.docker.internal:8082/realms/geostrat/protocol/openid-connect/userinfo"
scope = "openid profile email"
email_domains = ["*"]
skip_provider_button = true

upstreams = [
    "http://host.docker.internal:8080/"
]


api_routes = [
    "^/api/"
]

skip_auth_routes = [
    "^/login$",
    "^/login\\.html$",
    "^/auth\\.js$",
    "^/css/.*$",
    "^/js/.*$",
    "^/api/auth/me$"
]

session_store_type = "redis"
redis_connection_url = "redis://:redis123@host.docker.internal:6379"

pass_user_headers = true
pass_basic_auth = false
pass_access_token = false
pass_authorization_header = false
set_authorization_header = false
set_xauthrequest = false

cookie_name = "_oauth2_proxy_jbcd"
cookie_secret = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
cookie_secure = false
cookie_httponly = true
cookie_samesite = "lax"
cookie_csrf_expire = "15m"
cookie_csrf_per_request = true
cookie_csrf_samesite = "lax"

whitelist_domains = [
    "localhost:4180"
]