spring:
  application:
    name: geostrat
  thymeleaf:
    enabled: false
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
    error:
      include-stacktrace: never
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/geostrat}
    username: ${DATABASE_USERNAME:geostrat}
    password: ${DATABASE_PASSWORD:geostrat123}
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${APP_DATABASE_SCHEMA:geostrat}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_schema: ${APP_DATABASE_SCHEMA:geostrat}
    show_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080,http://localhost:4180}
    oauth2:
      client:
        provider:
          dex:
            issuer-uri: ${OIDC_ISSUER_URI:http://dex:5556/dex}
        registration:
          dex:
            client-id: ${OIDC_CLIENT_ID:geostrat-client}
            client-secret: ${OIDC_CLIENT_SECRET:EkQ8rE0gBkNDhqbaML5QP4XXNnn9tn2n}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: dex
            scope:
              - openid
              - profile
              - email

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG